# Generated by Django 3.2.3 on 2021-06-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal', models.IntegerField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longtitude', models.FloatField(null=True)),
                ('searchval', models.CharField(max_length=200)),
                ('blk_no', models.CharField(max_length=10, null=True)),
                ('road_name', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='hawkerstall',
            name='hours',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
