# Generated by Django 3.2.3 on 2021-07-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210717_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupbuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.IntegerField(blank=True, null=True)),
                ('areacollect', models.CharField(blank=True, max_length=100, null=True)),
                ('contactinfo', models.CharField(blank=True, max_length=100, null=True)),
                ('additionalinfo', models.CharField(blank=True, max_length=10000, null=True)),
                ('latorigin', models.FloatField(blank=True, null=True)),
                ('longorigin', models.FloatField(blank=True, null=True)),
                ('lat2', models.FloatField(blank=True, null=True)),
                ('long2', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
