# Generated by Django 3.2.3 on 2021-07-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210708_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='contributor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
