# Generated by Django 3.2.3 on 2021-08-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_groupbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='stallname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
