# Generated by Django 3.2.3 on 2021-07-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210710_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='email',
            field=models.ManyToManyField(blank=True, null=True, to='project.Email'),
        ),
    ]
