# Generated by Django 3.2.3 on 2021-07-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210703_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='ordered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='stallname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='deals',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='fooddelivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='freelance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='phonedelivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='project.Menu'),
        ),
    ]
