# Generated by Django 3.2.3 on 2021-07-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_report_stallname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
