# Generated by Django 3.2.3 on 2021-07-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210704_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hawkerstall',
            old_name='postal',
            new_name='number',
        ),
    ]
