# Generated by Django 3.2.3 on 2021-07-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawkerstall',
            name='postalcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hawkerstall',
            name='details',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
