# Generated by Django 3.2.3 on 2021-07-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_hawkerstall_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawkerstall',
            name='halal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='pricerange',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
