# Generated by Django 3.2.3 on 2021-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210715_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hawkerstall',
            name='image',
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='image1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='image2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='image3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='image4',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='hawkerstall',
            name='image5',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
